<<optimizer-name>>:
  <<parameter_name>>: <<value>>

# Full example (these constants have to match the __init__ arguments of the respective optimizer)
# cem-tf:
#   seed: null                          # If null, random seed based on datetime is used
#   mpc_horizon: 40                     # steps
#   cem_outer_it: 3                     # How many outer iterations to use
#   cem_initial_action_stdev: 0.5
#   num_rollouts: 200                   # How many rollouts per outer cem iteration
#   cem_stdev_min: 0.01
#   cem_best_k: 40
#   warmup: false
#   warmup_iterations: 250
#   predictor_specification: "ODE_TF"   # Can be "ODE", "ODE_TF", network/GP name (possibly with path) e.g. 'GRU-6IN-32H1-32H2-5OUT-0'/'SGP_30' or a name of a custom predictor. For more info see config_predictors in SI_Toolkit_ASF
